:uri-asciidoctor: http://asciidoctor.org
:icons: font
:source-highlighter: pygments
:nofooter:

== WebKey

== What is it?

Chrome extension empowering users to browse more with the keyboard  and less with the mouse.
It is a cVim fork adding more features

== Who is it for?

WebKey is dedicated to power users.

It follows Arch Linux philosophy by being *user-centric* not user-friendly. It is intended to fill the needs of those contributing to it rather than appeal to as many users as possible.

If you are familiar with vimperator/pentadactyl/vim, you will feel right at home. Otherwise, please consider using a beginner extension like vimium https://vimium.github.io/

== Installation

include::docs/installation.adoc[]

== Commands and settings

include::docs/commands.adoc[]

include::docs/settings.adoc[]

== Contribute

WebKey is always hungry for contributions and seeking improvements.
include::docs/contribute.adoc[]

== Thanks

These contributors shared their time and expertise freely.
include::docs/thanks.adoc[]

== Help & Tips

include::docs/tips.adoc[]

== Change Logs

include::docs/changelog.adoc[]
